### ISSUE TITLE
Test run in multiple threads

### ISSUE THREAD

**Issue by slawekjaranowski** [mockito/mockito-testng#20]
We can annotate test with:

```
    @Mock
    private MyType mock;

    @Test(threadPoolSize = 3, invocationCount = 8)
    public void testParallel() {
     ....
    }
```

In this case `MockitoTestNGListener` will not work as we want.
In current implementation `MockitoSession` is bind to current test instance, but `TestNG` create one test instance and run test in multiple thread.

Issue need more investigate how to resolve problem.

We must to check and discover how mocked field should be distinguished on one test instance  and multiple thread.

Please like / react on issue to we see how many people are interested this issue.

**Comment by slawekjaranowski** [comment]
This https://github.com/cbeust/testng/issues/1872 is probably connected.

**Comment by mlieshoff** [comment]
I strongly guess it throws **ConcurrentModificationExceptions** because of the usage of **HashMaps** instead of **ConcurrentHashMaps** in the **MockitoTestNGListener** class. The (not thread safe) handling of the fixtures seems to be a problem in the framework and related to the referenced issue. But at least the listener itself could be thread safe with changing the **Map** implementation and make life a bit easier :)

**Comment by ben-manes** [comment]
I ran into the `ConcurrentModificationException` error as well due to using TestNG's parallel methods support in its test runner. This makes this testng listener useless for a large suite because it requires forcing the test classes to be `@Test(singleThreaded=true)` which can significantly impact the execution time. This is distinctly different from `threadPoolSize` because different test methods are run concurrently.

In the simplest case, I had used Mockito as shorthand for dummy instances where I am testing a builder class so the mocks are never invoked or configured.

```console
java.util.ConcurrentModificationException
    at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1135)
    at org.mockito.testng.MockitoTestNGListener.beforeInvocation(MockitoTestNGListener.java:101)
    at org.testng.internal.invokers.InvokedMethodListenerInvoker.invokeListener(InvokedMethodListenerInvoker.java:55)
    at org.testng.internal.invokers.BaseInvoker.runInvokedMethodListeners(BaseInvoker.java:82)
    at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:651)
    at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
    at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
    at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
    at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
    at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
    at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:829)
```
